### ISSUE TITLE
Add linear search in python

### ISSUE THREAD

**Issue by 22shubh22** [khanchi97/Smvdu-Algos#115]
File is to be added here https://github.com/khanchi97/Smvdu-Algos/tree/master/search-algos/linear_search

**Comment by amitsharma1919** [comment]
I'm working on it. Will I have to fork this repository or the one you provided link to? Please tell me.
@22shubh22

**Comment by khanchi97** [comment]
closes #115

**Comment by khanchi97** [comment]
Already implemented!
