### ISSUE TITLE
DFS:Depth First Search >> Lang-CPP

### ISSUE THREAD

**Issue by khanchi97** [khanchi97/Smvdu-Algos#5]
You have to implement for search a point using DFS approach.
if you have some problem you can comment here.

**Comment by ajayaravindh** [comment]
@khanchi97  Should I be printing the order in which the DFS is performed or should I be searching for a particular node?

**Comment by khanchi97** [comment]
I think the best will be to print the order in which DFS is performed 😉

**Comment by ajayaravindh** [comment]
Solved by PR #88
